### ISSUE TITLE
Allow use of Upstream Proxy's DNS

### ISSUE THREAD

**Issue by stillunt1tled** [leproxy/leproxy#62]
Currently trying to use leproxy to forward my packets into the tor network.

I wanted to know if it is possible to use Tor's DNS so I can connect to hidden services. If it is not possible, maybe add it?

**Comment by clue** [comment]
This should in fact already be supported! Did you run into any problems? LeProxy does simply forward DNS hostnames to the next proxy when it has an upstream proxy defined like this (for example for Tor's default address):

```bash
$ php leproxy.php --proxy=localhost:9050
```

I hope this helps :+1:
