### ISSUE TITLE
Change upstream proxy while server is running

### ISSUE THREAD

**Issue by sky93** [leproxy/leproxy#63]
I have a proxy server (external). It changes its password every 10 minutes. The password is generated based on time.

How can I change upstream proxy password in leproxy while it's running?
I guess I need to change `$connector` while leproxy is running. I just don't know how.

**Comment by clue** [comment]
Hi @sky93, this is an interesting feature request!

Right now, you can configure the upstream proxy only through the command line which means you'll have to restart LeProxy with the new upstream configuration if your proxy changes.

In the future, we will provide a web based admin panel to change these settings (#52). Once this is ready, you can change this config while LeProxy is running and it should take effect immediately :+1:
