### ISSUE TITLE
how to get a username connections?

### ISSUE THREAD

**Issue by ghasemy50** [leproxy/leproxy#64]
hi,
i want to see one username has how many connections?
how can i get it separated by username?

**Comment by clue** [comment]
Hi @ghasemy50! I'm not sure I follow what you're trying to do, as it's a bit unclear what you're trying to achieve from the description you've posted.

LeProxy does not currently keep track of any statistics for privacy reasons. If also only supports a single user/password. This means there's currently no way to see how many connections a user has. You can take a look at the log output, perhaps this helps you?

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
