### ISSUE TITLE
Caching technique

### ISSUE THREAD

**Issue by JutGreg** [leproxy/leproxy#65]
Hey all,

Is there any way to implement a caching technique for images?

Thanks for the answer.

**Comment by clue** [comment]
Hi @JutGreg! LeProxy is designed to pass the request/response through as-is without any modification. If the destination site includes caching headers, these will also be included in the response headers from LeProxy.

What LeProxy does not do is modify anything about the request. While technically possible for plaintext HTTP, this won't work for encrypted HTTPS which is becoming more and more common nowadays, so I'm not sure it's really worth the effort.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
